/*
 * Copyright (c) 2020. Aarre Laakso
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.aarrelaakso.drawl;

import org.assertj.core.api.BDDSoftAssertions;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.junit.jupiter.api.*;

import static org.assertj.core.api.BDDAssertions.then;
import static org.junit.jupiter.api.Assertions.assertEquals;

@TestMethodOrder(MethodOrderer.Alphanumeric.class)
@DisplayName("Unit tests of Drawing with Circle shapes")
public class CircleDrawingTestProtected extends ShapeDrawingTestProtected
{

    Circle shape1;
    Circle shape2;
    Circle shape3;

    @BeforeEach
    @DisplayName("Given three default Circles")
    void givenTheeDefaultCircles()
    {
        this.shape1 = new Circle();
        this.shape2 = new Circle();
        this.shape3 = new Circle();
        super.shape1 = this.shape1;
        super.shape2 = this.shape2;
        super.shape3 = this.shape3;
    }

    @Test
    @DisplayName("RADIUS - EXPLICIT: When a square (100) drawing has two adjacent Circles, then their explicit radii are correct")
    final void radiusExplicitWhenASquare100DrawingHasTwoAdjacentCirclesThenTheirExplicitRadiiAreCorrect()
    {
        this.drawing.add(this.shape1);
        this.drawing.add(this.shape2);
        this.shape2.setRightOf(this.shape1);
        this.drawing.setExplicitHeight(100);
        this.drawing.setExplicitWidth(100);
        @Nullable final Number explicitRadius1 = this.shape1.getExplicitRadius();
        @Nullable final Number explicitRadius2 = this.shape2.getExplicitRadius();

        assertEquals(DrawlNumber.valueOf(25), explicitRadius1);
        assertEquals(DrawlNumber.valueOf(25), explicitRadius2);
    }

    @Test
    @DisplayName("RADIUS - IMPLICIT: When a square (100) drawing has two adjacent Circles, then their implicit radii are correct")
    void radiusImplicitWhenASquare100DrawingHasTwoAdjacentCirclesThenTheirImplicitRadiiAreCorrect()
    {
        this.drawing.add(this.shape1);
        this.drawing.add(this.shape2);
        this.shape2.setRightOf(this.shape1);
        this.drawing.setExplicitHeight(100);
        this.drawing.setExplicitWidth(100);
        final Number actualImplicitRadius1 = this.shape1.getImplicitRadius();
        final Number actualImplicitRadius2 = this.shape2.getImplicitRadius();
        @NotNull final Number expectedValue = DrawlNumber.HALF;

        assertEquals(expectedValue, actualImplicitRadius1);
        assertEquals(expectedValue, actualImplicitRadius2);
    }

    @Test
    @DisplayName("SVG: The SVG generated by a drawing with a Circle contains the string 'circle'")
    final void svgGeneratedByADrawingWithACircleContainsTheStringCircle()
    {
        final int radius = 4000;
        @NotNull final Circle circle = new Circle(DrawlNumber.valueOf(radius));
        this.drawing.add(circle);
        @NotNull final String svg = this.drawing.getSVG(100, 100);

        then(svg).contains("circle");
    }

    @Test
    @DisplayName("The SVG generated by a Shape contains the x- and y-coordinates")
    final void thenTheSVGGeneratedByAShapeContainsXAndYCoordinates(@NotNull final BDDSoftAssertions softly)
    {
        final int x = 50;
        final int y = 50;
        this.drawing.add(this.shape1);
        this.drawing.add(this.shape2);
        this.drawing.setExplicitDimensions(100, 100);
        this.shape1.setExplicitXPositionCenter(x);
        this.shape1.setExplicitYPositionCenter(y);
        @NotNull final String svg = this.drawing.getSVG();
        final String expectedSvgX = "cx='50'";
        final String expectedSvgY = "cy='50'";
        softly.then(svg).contains(expectedSvgX)
                .contains(expectedSvgY);
    }


}